# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Exemplo JAVA NAtivo

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    # Compilando com Java
    - name: Compilar o Projeto
      run: |
          cd src
          javac -cp . Main.java
          javac -cp . Teste.java
      
    # Executar o Projeto TESTE
    - name: Executado Projeto TESTE
      run: |
          cd src
          java -cp . Teste
      
    - uses: mr-smithers-excellent/docker-build-push@v6    
      name: Deploy no Docker 
      with:
        image: nisflei/app_f
        tags: latest
        registry: docker.io
        dockerfile: dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
